[build]
command = "npm install && npm run build"
publish="/build/client"
base="/react-router"

# Optional: Redirect root to frontend
[[redirects]]
  from = "/*"
  to = "/"
  status = 200
  [[redirects]]
  from = "/assets/*"
  to = "/.netlify/build/:splat"
  status = 200
