
# Redirect API routes to Netlify Functions
[[redirects]]
  from = "/api/tasks/*"
  to = "/.netlify/functions/tasks"
  status = 200

[[redirects]]
  from = "/api/rewards/*"
  to = "/.netlify/functions/rewards"
  status = 200

[[redirects]]
  from = "/api/wallet/*"
  to = "/.netlify/functions/wallet"
  status = 200
